#!/bin/sh

case $1 in
	"icon")
		[ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ] && echo "" && exit
		echo ""
		;;
	"status")
		[ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ] && echo "Off" && exit
		echo "On"
		;;
esac
