#!/bin/bash

log=$(cat $HOME/.cache/dunst.log)

# Split log values into array
readarray -t log_array <<< "$log"

case $1 in
    "timestamp")
        echo "${log_array[0]}"
        ;;
    "appname")
        echo "${log_array[1]}"
        ;;
    "body")
        count=$(echo -n "${log_array[2]}" | wc -c)
        if [ "$count" -le 18 ]; then
            echo "${log_array[2]}"
        else
            # Truncate body text to fit in notification
            echo "${log_array[2]::12}..."
        fi
        ;;
    "all")
        echo "${log_array[@]}"
        ;;
esac