#!/bin/sh

# Set playerctl to check for spotify first priority, and any player at second priority, and make the browser the last priority
PLAYER=$(playerctl -p spotify,%any,firefox,chromium,brave status)

if [ "$PLAYER" = "Playing" ]; then
    STATUS=""
elif [ "$PLAYER" = "Paused" ]; then
    STATUS=""
elif [ "$PLAYER" = "Stopped" ]; then
    STATUS=""
fi

echo $STATUS
