#!/bin/sh

# Simplfied because it was to complex and hacky, so removed the (on Browser) indication
PLAYER=$(playerctl -p spotify,%any,firefox,chromium,brave status)

if [ "$PLAYER" = "Playing" ]; then
    echo "Now Playing"
else
    echo "Music"
fi