#!/bin/sh

if ps -C spotify > /dev/null; then
    PLAYER="spotify"
fi

if [ -z "$PLAYER" ]; then
    if [ "$(playerctl -l | grep firefox)" ]; then
        STATUS=$(playerctl -p firefox status)

        if [ "$STATUS" = "Playing" ]; then
            STATUS="Now Playing (on Browser)"
        else
            STATUS="Music"
        fi
        
        printf "$STATUS"
    else 
        printf "Music"
    fi
fi

if [ "$PLAYER" = "spotify" ]; then
    STATUS=$(playerctl -p spotify status)

    if [ "$STATUS" = "Playing" ]; then
        STATUS="Now Playing"
    else
        STATUS="Music"
    fi
    
    if [ "$PLAYER" = "spotify" ]; then
        printf "$STATUS"
    fi
fi