#!/bin/sh

# Kinda hacky but I will improve this
PLAYER=$(playerctl -p spotify,%any,mpd -i firefox,chromium,brave status)
BROWSER=$(playerctl -p firefox,chromium,brave status)

if [ "$BROWSER" = "Playing" ]; then
  BROWSERMSG="true"
elif [ "$PLAYER" = "Playing" ]; then
  PLAYERMSG="true"
else
  echo "Music"
fi

if [ "$BROWSERMSG" = "true" ]; then
  echo "Now Playing (on Browser)"
elif [ "$PLAYERMSG" = "true" ]; then
  echo "Now Playing"
fi