#!/bin/bash

TITLE=$(playerctl metadata --format '{{ title }}')

if [ -z "$TITLE" ]; then
	echo "Nothing Playing";
else
	# Eww can't truncate Japanese characters.
	if [[ "$TITLE" =~ ^[一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+ ]]; then
		echo ${TITLE::10}...
	else
		echo $TITLE
	fi
fi
