#!/bin/bash
artist=$(playerctl metadata --format '{{ artist }}')
title=$(playerctl metadata --format '{{ title }}')
count=$(echo -n "$artist" | wc -c)

# Check if $title is "Advertisement" cause I don't have Spotify Premium :(
if [ "$title" = "Advertisement" ]; then
    echo "by Spotify"
else
    if [ -z "$artist" ]; then
        echo "by 404 Not Found";
    else
        echo "by $artist"
    fi
fi
