#!/bin/sh

# Change this to something above 0 if you have Spotify Premium.
# Defaults to 0 cause I don't have Premium :(
has_premium=1

if ps -C spotify > /dev/null; then
    PLAYER="spotify"
fi

if [ $has_premium -gt 0 ]; then
    if [ "$PLAYER" = "spotify" ]; then
        POSITION=$(playerctl position | sed 's/..\{6\}$//')
        DURATION=$(playerctl metadata mpris:length | sed 's/.\{6\}$//')

        printf "%0d:%02d " $((POSITION%3600/60)) $((POSITION%60))
        printf "/ %0d:%02d" $((DURATION%3600/60)) $((DURATION%60))
    fi
else
    printf " "
fi
