#!/bin/bash

title=$(playerctl metadata --format '{{ title }}')
count=$(echo -n "$title" | wc -c)

if [ -z "$title" ]; then
	echo "Nothing Playing";
else
	# Eww can't truncate Japanese characters.
	if [[ "$title" =~ ^[一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+ ]]; then
		echo ${title::10}...
	else
		echo $title
	fi
fi
