#!/bin/bash
pattern='/\G[^\x00-\x7F]/gm'
title=$(playerctl -p spotify metadata --format '{{ title }}')
count=$(echo -n "$title" | wc -c)
if [ -z "$title" ]; then
	echo "Not Playing";
else
	if [ "$count" -le 18 ]; then
        echo $title
	else	
		if [[ "$title" =~ [^\x00-\x7F] ]]; then
			echo $(playerctl metadata --format '{{ title }}' | awk '{ print substr($0, 1, 6) }')...
        elif [[ "$title" -le 15 ]]; then
            echo $(playerctl metadata --format '{{ title }}' | awk '{print $1, $2}')
        else
	    	echo $(playerctl metadata --format '{{ title }}' | awk '{print $1, $2, $3}')...
		fi
	fi
fi
