#!/bin/bash

tmp_dir="$HOME/.cache/eww/getart"
tmp_cover_path=$tmp_dir/cover.png
tmp_temp_path=$tmp_dir/temp.png

if [ ! -d $tmp_dir ]; then
	mkdir -p $tmp_dir
fi

artlink="$(playerctl -p spotify,$any,mpd,firefox,chromium,brave metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
artFromBrowser=$(playerctl metadata mpris:artUrl | sed 's/file:\/\///g')

if [ $(playerctl -p spotify,%any,firefox,chromium,brave,mpd metadata mpris:artUrl) ]; then
	curl -s "$artlink" --output $tmp_temp_path
elif [[ -n $artFromBrowser ]]; then
	cp $artFromBrowser $tmp_temp_path
else
	cp $HOME/.config/eww/assets/fallback.png $tmp_temp_path
fi

# an epic effekt
# convert $tmp_temp_path -alpha set -channel A -evaluate multiply 1.0  $tmp_cover_path
convert $tmp_temp_path -gravity center +repage -alpha set -channel A \
	-sparse-color Barycentric '%[fx:w*2/32],0 transparent  %[fx:w+0.5],0 opaque' \
	-evaluate multiply 0.45 \
	$tmp_cover_path
