#!/bin/bash

ARTIST=$(playerctl metadata --format '{{ artist }}')
TITLE=$(playerctl metadata --format '{{ title }}')

# Check if $title is "Advertisement" cause I don't have Spotify Premium :(         Deathemonic: How about using a spicetify adblocker (The Easy Way) or a adblock script https://github.com/abba23/spotify-adblock (The Chad Way)       Kizu: https://github.com/abba23/spotify-adblock to big to clone for my wifi lmao
if [ "$TITLE" = "Advertisement" ]; then
	echo "Spotify Free"
else
	if [ -z "$ARTIST" ]; then
		echo "Unknown Artist";
	else
		echo "by $ARTIST"
	fi
fi
