#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export WALLPAPER="$HOME/.config/bspwm/assets/wallpaper.png"

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Clear cache.
rm $HOME/.cache/dunst.log
rm $HOME/.cache/fake_battery_capacity

# Autostart Apps
$HOME/.local/bin/eww open bar &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Setup wallpaper
hsetroot -fill "$WALLPAPER"

# I hate mouse drift.
xset m 0 0

# Fix for eww bar not hiding on a fullscreen window.
$HOME/.config/bspwm/scripts/eww_fullscreen_fix.sh &

# Start MPD and mpDris2
exec mpd &
exec mpDris2 &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5

rule firefoxdeveloperedition        desktop=1 follow=on

rule discord                        desktop=2 follow=off
rule Code                           desktop=3
rule Steam                          desktop=4

rule Viewnior                       state=floating
rule mpv                            state=floating

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4

config window_gap                   16

config top_padding                  62
config left_padding                 12
config right_padding                12

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

start $HOME/.local/bin/brdr
# Fix windows being below bar
xdo lower -N eww-bar
