#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

mpd $HOME/.config/mpd/mpd.conf
$HOME/.local/bin/mpd-discord-rpc &
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

hsetroot -fill "$HOME/Pictures/Wallpapers/Gruvbox/gruvbox_waterfall_ig.png"
sh $HOME/.config/polybar/launch.sh

xset r rate 250 40

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

rule Vivaldi-stable                 desktop=^1
rule discord                        desktop=^2
rule code                           desktop=^3

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V VI VII VIII

config border_width                 20
config window_gap                   25

config top_padding                  35
config bottom_padding               0

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

outer='0x1d2021'   # outer
inner1='0x32302f'  # focused
inner2='0x282828'  # normal

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "4" -o "9" $* |:; }

initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
    done
