#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &
hsetroot -fill "$HOME/Pictures/Wallpapers/Stars.png"
sh $HOME/.config/polybar/launch.sh

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V VI VII

bspc config border_width         3
bspc config window_gap           25

bspc config top_padding          37
bspc config bottom_padding       0

bspc config normal_border_color  "#13141d"
bspc config active_border_color  "#13141d"
bspc config focused_border_color "#13141d"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bpsc rule -a Vivaldi-stable desktop=^1
bspc rule -a discord desktop=^2
bspc rule -a Code desktop=^3
bspc rule -a Thunar desktop=^4
bspc rule -a Spotify desktop=^5

bspc rule -a alacritty state=floating
